---
kind: pipeline
type: kubernetes
name: default

steps:
- name: docker  
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    repo: asegaml/doozy
    tag: 123
    username: asegaml
    password: get*mdm2kmp0jzc3FVC


trigger:
  event:
    exclude:
      - push
      - pull_request
